plugins {
    id 'java'
    id 'net.neoforged.gradle.userdev' version '7.0.80'
    id 'org.spongepowered.mixin' version '0.7.+'
}

base {
    archivesName = 'blockliftgun'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

minecraft {
    version = '1.21.1'
}

dependencies {
    implementation 'net.neoforged:neoforge:21.1.47'
}

mixin {
    add sourceSets.main, "blockliftgun.mixins.json"
}

tasks.withType(JavaCompile).configureEach {
    source.include "**/*.java"
}
